NET-Framework-MVC/Models/LivroModel.cs
using Npgsql;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace NET_Framework_MVC.Models
{
    public class LivroModel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public string Autor { get;set;}
        private static string ConnectionString = ConfigurationManager.ConnectionStrings["MinhaConexao"].ConnectionString;

        public LivroModel(int id, string titulo, string categoria, string autor)
        {
            Id = id;
            Titulo = titulo;
            Categoria = categoria;
            Autor = autor;
        }

        public LivroModel()
        {
        }

        public void add()
        {
            using (NpgsqlConnection connection = new NpgsqlConnection(ConnectionString))
            {
                connection.Open();


                string sql = "INSERT INTO livros (titulo, autor, categoria) VALUES (@titulo, @autor, @categoria)";

                using (NpgsqlCommand command = new NpgsqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@titulo", this.Titulo);
                    command.Parameters.AddWithValue("@autor", this.Autor);
                    command.Parameters.AddWithValue("@categoria", this.Categoria);

                    int rowsAffected = command.ExecuteNonQuery();

                    Console.WriteLine("Número de linhas afetadas: " + rowsAffected);
                }

               
            }
        }

        public static List<LivroModel> Todos()
        {
            List<LivroModel> livros = new List<LivroModel>();

            using (NpgsqlConnection connection = new NpgsqlConnection(ConnectionString))
            {
                connection.Open();

                string sql = "SELECT id, titulo, autor, categoria FROM livros";

                using (NpgsqlCommand command = new NpgsqlCommand(sql, connection))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            LivroModel livro = new LivroModel();
                            livro.Id = reader.GetInt32(0);
                            livro.Titulo = reader.GetString(1);
                            livro.Autor = reader.GetString(2);
                            livro.Categoria = reader.GetString(3);
                            



                            livros.Add(livro);
                        }
                    }
                }
            }

            return livros;

        }

    }
}

NET-Framework-MVC/Controllers/HomeController.cs
using NET_Framework_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NET_Framework_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.livros = LivroModel.Todos();
            return View(new
            {
                Livros = LivroModel.Todos(),
                Mensagem = "oi"
            });
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NET-Framework-MVC/Controllers/LivroController.cs
using NET_Framework_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NET_Framework_MVC.Controllers
{
    public class LivroController : Controller
    {
        // GET: Livro
        public ActionResult Index()
        {
            ViewBag.livros = LivroModel.Todos();
            return View(new
            {
                Livros = LivroModel.Todos()
            });
        }

        // GET: Livro/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Livro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Livro/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                LivroModel livro = new LivroModel();
                livro.Titulo = collection["Titulo"];
                livro.Autor = collection["Autor"];
                livro.Categoria = collection["Categoria"];

                livro.add();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Livro/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Livro/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Livro/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Livro/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NET-Framework-MVC/Views/Livro/Create.cshtml
@model NET_Framework_MVC.Models.LivroModel

@{
    ViewBag.Title = "Novo Livro";
}

<h2>Novo Livro</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <section class="card vw-100 ">
        <div class="card-header">
            <h3>Digite as informações do novo livro</h3>
        </div>
        <div class="card-body d-flex w-auto  justify-content-center" >
            <div class="form-horizontal ">
                <h4>Livro</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
                    
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label " })
                 
                        @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
              
                </div>

                <div class="form-group d-flex justify-content-end my-2">
           
                        <input type="submit" value="Salvar" class="btn btn-outline-primary" />
                  
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div>
                @Html.ActionLink("Voltar", "Index")
            </div>
        </div>

    </section>

   
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NET-Framework-MVC/Views/Livro/Index.cshtml
@{
    ViewBag.Title = "Lista Livros";
}
@using NET_Framework_MVC.Models;

<main class="container my-5">

    <div class="my-5">Todos os livros </div>
    <h1 class="my-5">Todos os livros </h1>


    @Html.ActionLink("Novo Livro", "Create", "Livro", new { }, new { @class = "btn btn-primary" })



    <table class="table table-hover table-borderless">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Titulo</th>
                <th scope="col">Autor</th>
                <th scope="col">Categoria</th>
            </tr>
        </thead>
        <tbody>
            @foreach (LivroModel livro in ViewBag.livros)
            {
                <tr>
                    <th scope="row">@livro.Id</th>
                    <td>@livro.Titulo</td>
                    <td>@livro.Autor</td>
                    <td>@livro.Categoria</td>
                </tr>
            }
        </tbody>
    </table>
</main>